services:
  videometaservice:
    image: ${DOCKER_REGISTRY-}videometaservice
    build:
      context: .
      dockerfile: VideoMetaService/Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB_CONNECTION_STRING=mongodb://admin:Test123!@mongo:27017
      - MONGODB_DATABASE_NAME=VideoMetaDB
      - SERVICEBUS_CONNECTION_STRING=${SERVICEBUS_CONNECTION_STRING}
      - SERVICEBUS_TOPIC_NAME=interactiveflix-topic
    ports:
      - 5175:5175
  mongo:
    image: mongo:latest
    container_name: mongodb-videometadata-container
    command: mongod --auth --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: VideoMetaDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Test123!

volumes:
  mongodb-data:
    driver: local  
