services:
  videometaservice:
    image: ${DOCKER_REGISTRY-}videometaservice
    env_file:
      - .env
    build:
      context: .
      dockerfile: VideoMetaService/Dockerfile
    ports:
      - 5175:5175
  mongo:
    image: mongo:latest
    container_name: mongodb-videometadata-container
    command: mongod --auth --bind_ip_all
    ports:
      - "27018:27018"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: VideoMetaDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Test123!

volumes:
  mongodb-data:
    driver: local  
