apiVersion: apps/v1
kind: Deployment
metadata:
  name: videometaservice-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: videometaservice-backend
  template:
    metadata:
      labels:
        app: videometaservice-backend
    spec:
      containers:
        - name: videometaservice-backend
          image: rikhendrix/videometaservice-backend:latest
          ports:
            - containerPort: 5175
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: videometaservice-secrets
                  key: mongodb-connection-string
            - name: MONGODB_DATABASE_NAME
              value: "VideoMetaDB"
            - name: SERVICEBUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: videometaservice-secrets
                  key: servicebus-connection-string
            - name: SERVICEBUS_TOPIC_NAME
              value: "interactiveflix-topic"
