apiVersion: v1
kind: Service
metadata:
  name: videometaservice-backend
spec:
  selector:
    app: videometaservice-backend
  ports:
    - protocol: TCP
      port: 5175
      targetPort: 5175
  type: ClusterIP
