apiVersion: v1
kind: Service
metadata:
  name: videometaservice-backend
spec:
  selector:
    app: videometaservice-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
